version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "recvCSVapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gj3dpur5jzba"
s3_prefix = "recvCSVapp"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
